### DISCUSSION TITLE
Has anyone gotten Ray to work on a Laravel Sail application? (MacOS)

### DISCUSSION THREAD

**Discussion by BlakeCThompson** [spatie/ray#508] [Q&A]
I've been trying for a long time now to get ray working on a laravel sail application running on Docker. I've followed all of the instructions given in the Ray documentation, installing ray, updating my ray.php's remote_path and local_path to the docker working directory and the project's root directory, and adding 
```
        extra_hosts:
            - "host.docker.internal:host-gateway"
```
to my docker-compose.yml file. (Shown at bottom). 
There seems to be an issue with Ray being able to connect to the host. When Ray tries to connect, it gets an error, "Could not resolve host: host.docker.internal", which is odd because, like I said, I've added the extra_hosts to my app's docker-compose entry.

Is there anybody out there that has gotten ray working on a laravel sail application running on Docker?

Here is a snippet of my docker-compose.yml file

```
# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.0
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.0/app
        ports:
            - '${APP_PORT:-8000}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        extra_hosts:
            - "host.docker.internal:host-gateway"
```
