### ISSUE TITLE
Not able to work ubuntu - docker

### ISSUE THREAD

**Issue by meminuygur** [spatie/ray#156]
**Describe the bug**
The project seems awesome ! 
I applied all required configs but not showing any data on Ray App. Is there anything i am missing ?

**Versions**
Ray version: 1.3.0

- spatie/ray package version: 1.6.0
- spatie/laravel-ray package version (if applicable): --
- using in magento2

PHP version: 7.4.13
Laravel version: --
Magento version: 2.4.1
Docker version: 20.10.2

**ray.php** content :
```php
<?php
return [
    /*
     *  The host used to communicate with the Ray app.
     */
    'host' => 'host.docker.internal',

    /*
     *  The port number used to communicate with the Ray app.
     */
    'port' => 23517,

    /*
     *  Absolute base path for your sites or projects in Homestead, Vagrant, Docker, or another remote development server.
     */
    'remote_path' => '/var/www',

    /*
     *  Absolute base path for your sites or projects on your local computer where your IDE or code editor is running on.
     */
    'local_path' => '/home/mehmet/phprojects/magento2',
];
```
docker-compose settings for apache2
```yaml
### Apache Server ########################################
    apache2:
      build:
        context: ./apache2
        args:
          - PHP_UPSTREAM_CONTAINER=${APACHE_PHP_UPSTREAM_CONTAINER}
          - PHP_UPSTREAM_PORT=${APACHE_PHP_UPSTREAM_PORT}
          - PHP_UPSTREAM_TIMEOUT=${APACHE_PHP_UPSTREAM_TIMEOUT}
          - DOCUMENT_ROOT=${APACHE_DOCUMENT_ROOT}
          - APACHE_INSTALL_HTTP2=${APACHE_INSTALL_HTTP2}
      volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
        - ${APACHE_HOST_LOG_PATH}:/var/log/apache2
        - ${APACHE_SITES_PATH}:/etc/apache2/sites-available
      ports:
        - "${APACHE_HOST_HTTP_PORT}:80"
        - "${APACHE_HOST_HTTPS_PORT}:443"
      depends_on:
        - php-fpm
      networks:
        - frontend
        - backend
      extra_hosts:
        - "host.docker.internal:host-gateway"
```

**To Reproduce**

**Expected behavior**
It should work.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 
 **Additional context**

**Comment by meminuygur** [comment]
I found the solution. The `host.docker.internal:host-gateway` parameter should be added on php-fpm container not on apache.

**Comment by sinnbeck** [comment]
What did you set as 'host-gateway' ? I assume that you set it to a 172.*.0.1 address?

**Comment by meminuygur** [comment]
here, check my config for php-fpm
```yaml
php-fpm:
      build:
        context: ./php-fpm
        args:
          - CHANGE_SOURCE=${CHANGE_SOURCE}
          - ......
          - ......
      volumes:
        - ./php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
        - docker-in-docker:/certs/client
      expose:
        - "9000"
      extra_hosts:
        - "dockerhost:${DOCKER_HOST_IP}"
        - "host.docker.internal:host-gateway"
      environment:
        - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
        - DOCKER_HOST=tcp://docker-in-docker:2376
        - ......
        - ......
      depends_on:
        - workspace
      networks:
        - backend
      links:
        - docker-in-docker
```
