### ISSUE TITLE
VScode integration appears broken in ray app 1.13.0

### ISSUE THREAD

**Issue by olivitek** [spatie/ray#327]
Prior to updating to 1.13.0 AppImage on Linux Mint 20 I was able to click on code links in the Ray app and automatically be routed to the relevant line in VSCode. Now, I receive a warning via a Visual Studio Code popup:

`Path does not exist. The path '/var/www/app/Http/Controllers/HomeController.php:106' does not seem to exist any more on the disk.`

![vscode-ray-err1](https://user-images.githubusercontent.com/7258221/109410300-9ccfb480-79ed-11eb-9992-fd347d733a91.png)

I'm running a Laravel 8 application in Docker. 

The ray app is successfully logging my code in real-time. Only the links back to VSCode are not working.

Here are the values in my .env file (which overrrides ray.php values)

```
RAY_HOST=host.docker.internal
RAY_PORT=23517
RAY_REMOTE_PATH=/var/www
RAY_LOCAL_PATH=/home/myusername/PROJECTS/clientproject
```

The RAY_LOCAL_PATH is the root of my Laravel 8 application. 

**Versions**
Ray version: 1.13.0
- spatie/ray package version: 1.19.4
- spatie/laravel-ray package version:  1.12.6

PHP version: 7.4.12
Laravel version: 8.14.0
VScode: 1.53.2 

**Desktop**
 - OS: Linux Mint
 - Version: 20 Ulyana

**Additional Info**
**Here's my docker-compose.yml file**

```
version: "3.7"
services:
  app:
    build:
      args:
        user: myuser
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: myclient
    container_name: myclient-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - myclient
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: mysql:5.7
    container_name: myclient-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_TCP_PORT: 3307
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3307:3307"
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - myclient

  nginx:
    image: nginx:alpine
    container_name: myclient-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - myclient
    extra_hosts:
      - "host.docker.internal:host-gateway"


  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8080:8080
    volumes:
     - /sessions
    networks:
     - myclient

networks:
  myclient:
    driver: bridge
 
```

Any advice much appreciated @freekmurze . Thanks for a great debugging tool!
